### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by melchua** [melchua/dancehive-reactapp#1]
As a user to the site,
I can create an account and login using facebook or google,
Once logged in, I get directed to the dashboard

- [x] Implement Firebase auth using their firebase webui
- [x] Only Facebook login for now
- [x] User has to be logged in to be able to access any of the dashboard or video pages
- [x] Non-logged in user can only see the landing page
- [x] Add a User model store if only to track if isLoggedIn across the site
- [x] When logged in success, user will be redirected to dashboard page
- [x] Dashboard page route should redirect to "please login" page if a user that's not logged in tries to just put in a route
- [x] When a user is logged in, the userstore should store the user object so it can get it's information populated 
- [x] When logged in, user profile image appears in Appbar along with displayname

**Comment by melchua** [comment]
My thinking here is that by limiting to facebook + google, we can discourage users from sharing with friends because they will essentially have to share their own facebook or google account. This could be an easier fix to our multiple account problems. Although, if they were really savvy the could create a new google email for eveyrone to share. It's tough to create a second facebook account in the same way.

**Comment by melchua** [comment]
So I think this is the strategy:

RC1 (March 2019): We only let users who sign in using FB access to the Dashboard, and the free videos that are available. 

RC2 (mid May / early June 2019): We use the same Firebase list of users with a Stripe integration. I think using Firebase admin tools will allow us to add extra user data to confirm if they are paid or unpaid users. This will take some work and testing.

**Comment by melchua** [comment]
Resource on cloud functions and triggers to create a profile:

https://bigcodenerd.org/create-user-profile-firestore-authentication/

**Comment by melchua** [comment]
ok ok, I get it now:

https://github.com/firebase/firebaseui-web-react
https://github.com/firebase/firebaseui-web

Using the options in the config and callbacks we can create a user profile, as well as set the state for signed in or not. We can use the auth() methods as well to check if signed in / out etc.

Get er' done!

**Comment by melchua** [comment]
- [ ] Hook in isLoggedIn store to firebase page
- [ ] Write action to update store (toggle upon login / logout)
- [ ] We can now tell when a user is logged in or out

Stretch
- [ ] Should we save to local storage to keep the user logged in?or is this stretch?
- [ ] Add user to user database in firestore when they log in if they don't already exist

**Comment by melchua** [comment]
Current blocker is enabling protected routes. Will chat with Nima on this to get some help.

**Comment by melchua** [comment]
This will give some insight to page refresh issue:
https://www.reddit.com/r/vuejs/comments/8q7xpz/firebase_auth_logs_in_but_redirects_to_login_at/

**Comment by melchua** [comment]
This could be the right strategy:
https://spectrum.chat/mobx-state-tree/general/create-mst-model-from-observable~c40326e7-0623-494e-9c71-496bbd314a7a

**Comment by melchua** [comment]
Maybe the solution is to add a reaction, so that everytime there's a change to that one property, the side effect is that it redirects you to the appropriate page.

**Comment by melchua** [comment]
@Jeffreypang911  you'll have to show me the issues you were facing with firebase.  That def needs to be fixed before we deploy for VancitySBK
